services:
  backend:
    image: ghcr.io/febbyyyyh/titik-jeda-backend:${IMAGE_TAG:-main}
    pull_policy: always
    volumes:
      - backend_uploads:/app/uploads

  frontend:
    image: ghcr.io/febbyyyyh/titik-jeda-frontend:${IMAGE_TAG:-main}
    pull_policy: always

volumes:
  backend_uploads:
