version: "3.8"

services:
  # 1. CONTAINER DATABASE (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: mental_health_app
      MYSQL_ROOT_PASSWORD: titikjeda123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -ptitikjeda123 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  # 2. CONTAINER BACKEND (Express JS)
  backend:
    build: ./backend
    container_name: express_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=titikjeda123
      - DB_NAME=mental_health_app
    # 💡 SUNTIKAN FILE .ENV BACKEND:
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
        

  # 3. CONTAINER FRONTEND (Vite React)
  frontend:
    build: ./titik-jeda
    container_name: react_frontend
    restart: always
    ports:
      - "3001:80"
    volumes:
      - ./titik-jeda:/app         
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mysql_data:
